inputtype: HermesCSVOut
numheader: 1
delimiter: ','
columntograph:
    Graph01:
        graphtype: line
        title: Fertilizer
        columns:
            - Date
            - SumFert
            - solutionSumFert
        datecolumn: Date
    Graph02:
        graphtype: ThemeRiver
        title: Nmin by layer
        columns:
            - Nmin0-1
            - Nmin1-2
            - Nmin2-3
            - Nmin3-4
            - Nmin4-5
            - Nmin5-6
            - Nmin6-7
            - Nmin7-8
            - Nmin8-9
            - Date
        datecolumn: 'Date'
    Graph03:
        graphtype: line
        title: Biomass
        columns:
            - abovegrDryM
            - Yield
            - LAI
            - Date
        datecolumn: Date
    Graph04:
        graphtype: line
        title: soil Water 
        columns:
            - SoilW 1
            - SoilW 2
            - SoilW 3
            - SoilW 4
            - SoilW 5
            - SoilW 6
            - SoilW 7
            - SoilW 8
            - SoilW 9
            - Date
        columnview: 
            - operation: sum
              name: soil 1-3
              multiply: 100
              columns:
                - SoilW 1
                - SoilW 2
                - SoilW 3
            - operation: sum
              name: soil 4-6
              columns:
                - SoilW 4
                - SoilW 5
                - SoilW 6
            - operation: avg
              name: soil 7-9
              columns:
                - SoilW 7
                - SoilW 8
                - SoilW 9
            - operation: diff
              name: soil difference 7-8
              columns:
                - SoilW 7
                - SoilW 8
            - operation: dailydifference
              name: soil daily difference 1
              columns:
                - SoilW 1
    Graph05:
        graphtype: line
        title: AutomIrrig and Precip
        columns:
            - AutomIrrig
            - Precip
            - Date
        columnview: 
            - operation: none
              name: AutomIrrig in mm
              multiply: 100
              columns:
                - AutomIrrig
            - operation: none
              name: Precip in mm
              multiply: 100
              columns:
                - Precip
                
        datecolumn: Date
    Graph06:
        graphtype: line
        title: Wp
        columns:
            - WP 1
            - WP 4
            - WP 7
            - Date
        datecolumn: Date
    Graph07:
        graphtype: circel
        title: FC
        columns:
            - FC 1
            - FC 4
            - FC 7
            - Date
        datecolumn: Date
    Graph08:
        graphtype: line
        title: stage
        columns:
            - Stage
            - Date
        datecolumn: Date
    Graph09:
        graphtype: line
        title: Bio time
        columns:
            - BiolTime_SumDeg
            - Date
        datecolumn: Date
    Graph10:
        graphtype: line
        title: N crop
        columns:
            - N crop
            - Date
        datecolumn: Date
    Graph11:
        graphtype: line
        title: W suffic
        columns:
            - W suffic
            - Date
        datecolumn: Date
    Graph12:
        graphtype: line
        title: Poresize
        columns:
            - PoreSize 1
            - PoreSize 4
            - PoreSize 7
            - Date
        datecolumn: Date
    Graph13:
        graphtype: line
        title: Soillayroot
        columns:
            - SoilLayRoot
            - Date
        datecolumn: Date
    
        